# Generated by Django 4.1.2 on 2023-01-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_player_esports_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='esports_team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
