# Generated by Django 4.1.2 on 2023-01-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_player_esports_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_player', models.CharField(default='#', max_length=255)),
                ('kd', models.FloatField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stat'),
        ),
    ]
