# Generated by Django 4.1.2 on 2023-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_match_tournament_matches_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
    ]
